### ISSUE TITLE
Priv bug

### ISSUE THREAD

**Issue by DeletedUser56** [NoNameDude/Minetest-wings#1]
@NoNameDude 
--While Holding the wings
![2021-04-07-175120_1920x1080_scrot](https://user-images.githubusercontent.com/81821021/113939568-297a4900-97ca-11eb-8c03-02ae1f614937.png)
--after holding the wings.
![2021-04-07-175129_1920x1080_scrot](https://user-images.githubusercontent.com/81821021/113939589-2ed79380-97ca-11eb-906b-a27481a9e8f4.png)

**Comment by NoNameDude** [comment]
Fixed now a player should only get the fly privs removed!
